# Generated by Django 4.1.7 on 2023-03-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnituremodel',
            name='view_click',
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
