# Generated by Django 4.1.7 on 2023-03-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_furnituremodel_view_click_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituremodel',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
