# Generated by Django 4.1.7 on 2023-03-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_furnituremodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituremodel',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
