# Generated by Django 4.1.7 on 2023-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_furnituremodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='github_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
