# Generated by Django 4.1.7 on 2023-03-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default='aboutus.jpg', upload_to='users/'),
        ),
    ]
