# Generated by Django 4.1.7 on 2023-03-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnituremodel',
            name='user',
        ),
    ]
