# Generated by Django 4.1.7 on 2023-03-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_furnituremodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, max_length=5),
        ),
    ]
