# Generated by Django 4.1.7 on 2023-03-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_furnituremodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
