# Generated by Django 4.1.7 on 2023-03-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_furnituremodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituremodel',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
