# Generated by Django 4.1.7 on 2023-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_furnituremodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='image',
            field=models.ImageField(null=True, upload_to='blogs/'),
        ),
    ]
