# Generated by Django 4.1.7 on 2023-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_furnituremodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
