# Generated by Django 4.1.7 on 2023-03-22 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_furnituremodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='image',
            field=models.ImageField(null=True, upload_to='blogs/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
