# Generated by Django 4.1.7 on 2023-03-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_furnituremodel_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='ContactUSModel',
        ),
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'ordering': ('-id',), 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
    ]
