# Generated by Django 4.1.7 on 2023-03-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_contactusmodel_created_at_contactusmodel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusmodel',
            name='message',
        ),
    ]
