# Generated by Django 4.1.7 on 2023-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_contactusmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='message',
            field=models.CharField(max_length=300, verbose_name='message'),
        ),
    ]
