# Generated by Django 4.1.7 on 2023-03-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_alter_furnituremodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
    ]
