# Generated by Django 4.1.7 on 2023-03-22 21:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_usermodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
