# Generated by Django 4.1.7 on 2023-03-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_alter_furnituremodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
            },
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='colors',
            field=models.ManyToManyField(related_name='fColors', to='web.colorsmodel', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='furnituremodel',
            name='tags',
            field=models.ManyToManyField(related_name='fTags', to='web.tagsmodel', verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='furnituremodel',
            name='size',
            field=models.ManyToManyField(related_name='fSizes', to='web.sizemodel', verbose_name='size'),
        ),
    ]
