# Generated by Django 4.1.7 on 2023-03-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_sizemodel_alter_furnituremodel_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
    ]
