# Generated by Django 4.1.7 on 2023-03-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_colorsmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furnituremodel',
            old_name='size',
            new_name='sizes',
        ),
    ]
