# Generated by Django 4.1.7 on 2023-03-23 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_rename_size_furnituremodel_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web.categorymodel', verbose_name='category'),
        ),
    ]
