# Generated by Django 4.1.7 on 2023-03-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_furnituremodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furnituremodel',
            old_name='category',
            new_name='categories',
        ),
    ]
