# Generated by Django 4.1.7 on 2023-03-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_rename_category_furnituremodel_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituremodel',
            name='real_price',
            field=models.FloatField(default=0, verbose_name='real price'),
        ),
    ]
