# Generated by Django 4.1.7 on 2023-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_furnituremodel_real_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
    ]
