# Generated by Django 4.1.7 on 2023-03-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_faqmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqmodel',
            options={'ordering': ('-id',), 'verbose_name': 'faq', 'verbose_name_plural': 'faqs'},
        ),
    ]
