# Generated by Django 4.1.7 on 2023-03-24 10:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_alter_faqmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituremodel',
            name='short_description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
