# Generated by Django 4.1.7 on 2023-03-24 10:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_furnituremodel_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='short_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
