# Generated by Django 4.1.7 on 2023-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_alter_furnituremodel_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='email',
            field=models.EmailField(max_length=32, verbose_name='email'),
        ),
    ]
