# Generated by Django 4.1.7 on 2023-03-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_alter_contactusmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='email',
            field=models.EmailField(max_length=45, verbose_name='email'),
        ),
    ]
