# Generated by Django 4.1.7 on 2023-03-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default='users/avatar.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
