# Generated by Django 4.1.7 on 2023-03-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituremodel',
            name='image',
            field=models.ImageField(upload_to='blogs/%Y/%m/%d/', verbose_name='image'),
        ),
    ]
