# Generated by Django 4.1.7 on 2023-03-25 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_alter_furnituremodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='github_username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='github username'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='instagram username'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telegram username'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='twitter username'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default='users/avatar.png', upload_to='users/%Y/%m/%d/', verbose_name='user image'),
        ),
        migrations.AlterField(
            model_name='wishlistmodel',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='wishlist', to='web.furnituremodel', verbose_name='furniture'),
        ),
        migrations.AlterField(
            model_name='wishlistmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='wishlistuser', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
