# Generated by Django 4.1.7 on 2023-03-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_alter_categorymodel_name_alter_usermodel_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizemodel',
            name='size',
            field=models.CharField(max_length=6, verbose_name='size'),
        ),
    ]
